name: Build Raspberry Pi Image

on:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git wget cpio unzip rsync bc \
            python3 file bison flex libssl-dev

      - name: Configure rpi2 Buildroot
        run: |
          cd buildroot

          make raspberrypi2_defconfig

          cat ../config-overrides/rpi2 >> .config

          make olddefconfig

      - name: Build rpi2 image
        run: |
          cd buildroot
          make -j$(nproc)

      - name: Upload image
        uses: actions/upload-artifact@v6
        with:
          name: rpi2-image
          path: buildroot/output/images/sdcard.img
