name: Build Raspberry Pi 3 Image

on:
  push:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git wget cpio unzip rsync bc \
            python3 file bison flex libssl-dev

      - name: Configure Buildroot
        run: |
          cd buildroot
          make BR2_DEFCONFIG=../configs/rpi3_defconfig defconfig

      - name: Build image
        run: |
          cd buildroot
          export FORCE_UNSAFE_CONFIGURE=1
          make -j$(nproc)

      - name: Upload image
        uses: actions/upload-artifact@v6
        with:
          name: rpi3-image
          path: buildroot/output/images/*
