name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g. 1.2.3 or v1.2.3)"
        required: true

permissions:
  contents: write
  actions: read

env:
  VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Run pimod builder
        uses: Nature40/pimod@master
        with:
          pifile: Pifile

      - name: Upload image
        uses: actions/upload-artifact@v6
        with:
          name: image
          path: image.img

  release:
    name: Create GitHub Release
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: "main"

      - name: Download artifacts
        uses: actions/download-artifact@v7

      - name: List files
        run: |
          ls -R

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ startsWith(env.VERSION, 'v') && env.VERSION || format('v{0}', env.VERSION) }}
          name: ${{ startsWith(env.VERSION, 'v') && env.VERSION || format('v{0}', env.VERSION) }}
          generate_release_notes: true
          overwrite_files: true
          files: |
            image.img
